/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2024-08-29 03:00:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1724823152000L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1724898033536L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    ");

    	String userid =(String) session.getAttribute("userid");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>관리자모드</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/fonts.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/remixicon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/photo-gallery.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/pycs-layout.jquery.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container position-relative pl-300\">\r\n");
      out.write("       <header class=\"position-absolute\">\r\n");
      out.write("          <div class=\"logo\"><a href=\"#\"><img src=\"images/logo.png\" alt=\"kdt community\"></a></div>\r\n");
      out.write("          ");

          	if(userid == null){
          
      out.write("\r\n");
      out.write("          <form id=\"loginform\" class=\"login\" method=\"post\" action=\"loginok\">\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" name=\"userid\" id=\"userid\" placeholder=\"아이디\">\r\n");
      out.write("             <input type=\"password\" class=\"form-control\" name=\"userpass\" id=\"userpass\" placeholder=\"비밀번호\">\r\n");
      out.write("             <div class=\"text-right\"><label><input type=\"checkbox\" name=\"rid\" id=\"rid\" value=\"ok\" /> 아이디 저장</label></label></div>\r\n");
      out.write("             <button type=\"submit\" class=\"btn btn-success btn-block\">로 그 인</button>\r\n");
      out.write("          </form>\r\n");
      out.write("          <div class=\"d-flex justify-content-between px-2 mb-5\">\r\n");
      out.write("            <a href=\"#\">아이디/비밀번호 찾기</a>\r\n");
      out.write("            <a href=\"register.jsp\">회원가입</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");

          }else{
          
      out.write("\r\n");
      out.write("          <div id=\"loginform\" class=\"login\">\r\n");
      out.write("          	<h5 class=\"text-center\">\r\n");
      out.write("          		");
      out.print(userid );
      out.write("님 로그인\r\n");
      out.write("          	</h5>\r\n");
      out.write("          	<p class=\"text-center\">\r\n");
      out.write("          	 	<a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("          	</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          <div>이미지배너</div>\r\n");
      out.write("       </header>");
      out.write("\r\n");
      out.write("<script src=\"js/photo-gallery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("          <div class=\"col-6\">\r\n");
      out.write("            <div class=\"comu-box\">\r\n");
      out.write("               <h2>Our Gallery</h2>\r\n");
      out.write("               <div class=\"photos-gallery clearfix\">\r\n");
      out.write("                <!--loop -->\r\n");
      out.write("                   <div class=\"picture\">\r\n");
      out.write("                      <a href=\"#\"><img src=\"images/upload/001.jpg\" alt=\"001\">\r\n");
      out.write("                         <div class=\"txt-box\">제목1입니다.제목4입니다.</div>\r\n");
      out.write("                      </a>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"picture\">\r\n");
      out.write("                      <a href=\"#\"><img src=\"images/upload/002.jpg\" alt=\"002\">\r\n");
      out.write("                        <div class=\"txt-box\">제목2입니다.제목4입니다.</div>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   <div class=\"picture\">\r\n");
      out.write("                      <a href=\"#\"><img src=\"images/upload/003.jpg\" alt=\"003\">\r\n");
      out.write("                        <div class=\"txt-box\">제목3입니다.제목4입니다.</div>\r\n");
      out.write("                      </a>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"picture\">\r\n");
      out.write("                      <a href=\"#\"><img src=\"images/upload/004.jpg\" alt=\"004\">\r\n");
      out.write("                        <div class=\"txt-box\">제목4입니다.제목4입니다.</div>\r\n");
      out.write("                      </a>\r\n");
      out.write("                   </div>\r\n");
      out.write("                 <!-- /loop -->  \r\n");
      out.write("               </div> \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-6\">\r\n");
      out.write("            <div class=\"comu-box\">\r\n");
      out.write("               <h2>Notice</h2>\r\n");
      out.write("   \r\n");
      out.write("               <ul class=\"noticeul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice1\">공지</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>     \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice2\">알림</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice3\">이벤트</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice1\">공지</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice4\">추천</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice1\">공지</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice1\">공지</span> 공지사항 게시판 입니다. 공지사항 게시판 입니다.\r\n");
      out.write("                        공지사항 게시판 입니다.\r\n");
      out.write("                        공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"notice notice1\">공지</span> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>               \r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-6\">\r\n");
      out.write("            <div class=\"comu-box\">\r\n");
      out.write("               <h2>Blog</h2>\r\n");
      out.write("               <ul class=\"blogul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\" class=\"blogs\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                           <img src=\"images/upload/006.webp\" alt=\"006\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-text\">\r\n");
      out.write("                           <h3>기사의 제목을 넣음</h3>\r\n");
      out.write("                           <p>정당의 설립은 자유이며, 복수정당제는 보장된다. 법률안에 이의가 있을 때에는 대통령은 제1항의 기간내에 이의서를 붙여 국회로 환부하고, 그 재의를 요구할 수 있다. 국회의 폐회중에도 또한 같다.</p>\r\n");
      out.write("                           <p>재의의 요구가 있을 때에는 국회는 재의에 붙이고, 재적의원과반수의 출석과 출석의원 3분의 2 이상의 찬성으로 전과 같은 의결을 하면 그 법률안은 법률로서 확정된다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a> \r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\" class=\"blogs\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                           <img src=\"images/upload/006.webp\" alt=\"006\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-text\">\r\n");
      out.write("                           <h3>기사의 제목을 넣음</h3>\r\n");
      out.write("                           <p>정당의 설립은 자유이며, 복수정당제는 보장된다. 법률안에 이의가 있을 때에는 대통령은 제1항의 기간내에 이의서를 붙여 국회로 환부하고, 그 재의를 요구할 수 있다. 국회의 폐회중에도 또한 같다.</p>\r\n");
      out.write("                           <p>재의의 요구가 있을 때에는 국회는 재의에 붙이고, 재적의원과반수의 출석과 출석의원 3분의 2 이상의 찬성으로 전과 같은 의결을 하면 그 법률안은 법률로서 확정된다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a> \r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\" class=\"blogs\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                           <img src=\"images/upload/006.webp\" alt=\"006\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-text\">\r\n");
      out.write("                           <h3>기사의 제목을 넣음</h3>\r\n");
      out.write("                           <p>정당의 설립은 자유이며, 복수정당제는 보장된다. 법률안에 이의가 있을 때에는 대통령은 제1항의 기간내에 이의서를 붙여 국회로 환부하고, 그 재의를 요구할 수 있다. 국회의 폐회중에도 또한 같다.</p>\r\n");
      out.write("                           <p>재의의 요구가 있을 때에는 국회는 재의에 붙이고, 재적의원과반수의 출석과 출석의원 3분의 2 이상의 찬성으로 전과 같은 의결을 하면 그 법률안은 법률로서 확정된다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a> \r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-6\">\r\n");
      out.write("            <div class=\"comu-box\">\r\n");
      out.write("               <h2>Community</h2>\r\n");
      out.write("               <ul class=\"noticeul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>     \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"blank\"></span><i class=\"ri-corner-down-right-line\"></i> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        <span class=\"blank\"></span><span class=\"blank\"></span><i class=\"ri-corner-down-right-line\"></i> 공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                         공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                         공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                         공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                        공지사항 게시판 입니다. 공지사항 게시판 입니다.\r\n");
      out.write("                        공지사항 게시판 입니다.\r\n");
      out.write("                        공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>  \r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"#\">\r\n");
      out.write("                         공지사항 게시판 입니다.\r\n");
      out.write("                     </a>\r\n");
      out.write("                     <span class=\"ndate\">2024.07.31</span>\r\n");
      out.write("                  </li>               \r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <footer>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                <h4 class=\"text-center\">Copyright</h4>\r\n");
      out.write("             </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
