/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2024-08-30 00:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1724823152000L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1724898033536L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    ");

    	String userid =(String) session.getAttribute("userid");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>관리자모드</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/fonts.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/remixicon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/photo-gallery.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/pycs-layout.jquery.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container position-relative pl-300\">\r\n");
      out.write("       <header class=\"position-absolute\">\r\n");
      out.write("          <div class=\"logo\"><a href=\"#\"><img src=\"images/logo.png\" alt=\"kdt community\"></a></div>\r\n");
      out.write("          ");

          	if(userid == null){
          
      out.write("\r\n");
      out.write("          <form id=\"loginform\" class=\"login\" method=\"post\" action=\"loginok\">\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" name=\"userid\" id=\"userid\" placeholder=\"아이디\">\r\n");
      out.write("             <input type=\"password\" class=\"form-control\" name=\"userpass\" id=\"userpass\" placeholder=\"비밀번호\">\r\n");
      out.write("             <div class=\"text-right\"><label><input type=\"checkbox\" name=\"rid\" id=\"rid\" value=\"ok\" /> 아이디 저장</label></label></div>\r\n");
      out.write("             <button type=\"submit\" class=\"btn btn-success btn-block\">로 그 인</button>\r\n");
      out.write("          </form>\r\n");
      out.write("          <div class=\"d-flex justify-content-between px-2 mb-5\">\r\n");
      out.write("            <a href=\"#\">아이디/비밀번호 찾기</a>\r\n");
      out.write("            <a href=\"register.jsp\">회원가입</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");

          }else{
          
      out.write("\r\n");
      out.write("          <div id=\"loginform\" class=\"login\">\r\n");
      out.write("          	<h5 class=\"text-center\">\r\n");
      out.write("          		");
      out.print(userid );
      out.write("님 로그인\r\n");
      out.write("          	</h5>\r\n");
      out.write("          	<p class=\"text-center\">\r\n");
      out.write("          	 	<a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("          	</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          <div>이미지배너</div>\r\n");
      out.write("       </header>");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-12\">\r\n");
      out.write("     <div class=\"bg-white rg\">\r\n");
      out.write("       <h1 class=\"text-center py-5\">회원가입</h1>\r\n");
      out.write("       <p class=\"text-center mb-5\">저의 커뮤니티 웹에 온 것을 환영합니다.</p>\r\n");
      out.write("       <form name=\"registerform\" id=\"registerform\" action=\"registerok\" method=\"post\">\r\n");
      out.write("          <ul class=\"registerul\">\r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"userid\" class=\"col-2 text-right\">아이디</label>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                   <input type=\"text\" name=\"userid\" id=\"usrid\" placeholder=\"아이디\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"userpass\" class=\"col-2 text-right\">비밀번호</label>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                   <input type=\"password\" name=\"userpass\" id=\"usrpass\" placeholder=\"비밀번호\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"reuserpass\" class=\"col-2 text-right\">비밀번호확인</label>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                   <input type=\"password\" name=\"reuserpass\" id=\"reusrpass\" placeholder=\"비밀번호확인\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"username\" class=\"col-2 text-right\">이름</label>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                   <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"이름\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"\" class=\"col-2 text-right\">이메일</label>\r\n");
      out.write("                <div class=\"col-3\">\r\n");
      out.write("                   <input type=\"text\" id=\"emailid\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <span>@</span>\r\n");
      out.write("                <div class=\"col-3\">\r\n");
      out.write("                   <select class=\"form-control emailgroup\" id=\"emailDomain\">\r\n");
      out.write("                      <option value=\"\">도메인 선택</option>\r\n");
      out.write("                      <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                      <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("                      <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("                      <option value=\"act\">직접입력</option>\r\n");
      out.write("                   </select>\r\n");
      out.write("                   <input type=\"hidden\" name=\"email\" id=\"email\" value=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-3\">   \r\n");
      out.write("                   <input type=\"text\" id=\"emailDomain2\" class=\"form-control emailgroup\">\r\n");
      out.write("                </div>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"\" class=\"col-2 text-right\">전화번호</label>\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                   <input type=\"text\" id=\"tel1\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                -\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                   <input type=\"text\" id=\"tel2\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                -\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                   <input type=\"text\" id=\"tel3\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"hidden\" name=\"tel\" id=\"tel\" />\r\n");
      out.write("             </li>   \r\n");
      out.write("             <li class=\"d-flex py-4\">\r\n");
      out.write("                <label for=\"\" class=\"col-2 text-right\">주소</label>\r\n");
      out.write("                <div class=\"col-10 row mb-4\">        \r\n");
      out.write("                    <div class=\"col-3 mb-3\">\r\n");
      out.write("                       <input type=\"text\" id=\"postcode\" readonly class=\"form-control\" name=\"postcode\" placeholder=\"우편번호\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3 mb-3\">\r\n");
      out.write("                       <button type=\"button\" onclick=\"execDaumPostcode()\" class=\"btn btn-secondary\">우편번호</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6 mb-3\"></div>\r\n");
      out.write("                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                       <input type=\"text\" id=\"address\" readonly name=\"useraddr1\" class=\"form-control\" placeholder=\"주소\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                       <input type=\"text\" id=\"detailAddress\" name=\"useraddr2\" class=\"form-control\" placeholder=\"상세주소\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6 mb-3\">\r\n");
      out.write("                       <input type=\"text\" id=\"extraAddress\" name=\"useraddrexc\" class=\"form-control\" placeholder=\"참고항목\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("             </li>    \r\n");
      out.write("             <li class=\"text-center pt-1 pb-5\">\r\n");
      out.write("                   <button type=\"reset\" class=\"btn btn-warning py-2 px-5 mx-2\">취소</button>\r\n");
      out.write("                   <button type=\"submit\" class=\"btn btn-success py-2 px-5 mx-2\">전송</button>\r\n");
      out.write("             </li>      \r\n");
      out.write("          </ul>\r\n");
      out.write("       </form>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <footer>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                <h4 class=\"text-center\">Copyright</h4>\r\n");
      out.write("             </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
